server:
  port: 8098
  error:
    include-message: always

spring:
  application:
    name: product-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8877
